// <auto-generated />
namespace Lab11_Infraestructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class v5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v5));
        
        string IMigrationMetadata.Id
        {
            get { return "201911032103098_v5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
